version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/tabsleeper
    docker:
      - image: circleci/node:13.6.0
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@6.14.1'
      - run: ./script/setup
      - run: ./script/build
      - run: ./script/package
      - store_artifacts:
          path: 'output/packages'
          destination: 'packages'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master
  build-release-tag:
    jobs:
      - build:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
